package com.example.mviexample.designsystem.theme

import androidx.compose.ui.graphics.Color

internal val Primary = Color(0xFF002D5C)
internal val OnPrimary = Color(0xFFFFFFFF)
internal val PrimaryContainer = Color(0xFFD6E3FF)
internal val OnPrimaryContainer = Color(0xFF001B3D)
internal val Secondary = Color(0xFF00A39C)
internal val OnSecondary = Color(0xFF00201E)
internal val SecondaryContainer = Color(0xFFB2F2ED)
internal val OnSecondaryContainer = Color(0xFF00201E)
internal val Tertiary = Color(0xFF6C4FF6)
internal val OnTertiary = Color(0xFFFFFFFF)
internal val TertiaryContainer = Color(0xFFE8DFFF)
internal val OnTertiaryContainer = Color(0xFF1F006A)
internal val Error = Color(0xFFC62828)
internal val OnError = Color(0xFFFFFFFF)
internal val ErrorContainer = Color(0xFFFFDAD6)
internal val OnErrorContainer = Color(0xFF410002)
internal val Background = Color(0xFFF5F7FA)
internal val OnBackground = Color(0xFF141B26)
internal val Surface = Color(0xFFFFFFFF)
internal val OnSurface = Color(0xFF141B26)
internal val SurfaceVariant = Color(0xFFE3E8F0)
internal val OnSurfaceVariant = Color(0xFF5B6472)
internal val Outline = Color(0xFF8A93A3)
internal val OutlineVariant = Color(0xFFCBD2DC)
internal val Scrim = Color(0xFF001B3D)
internal val Gold = Color(0xFFF2B705)
internal val White = Color(0xFFFFFFFF)

internal val DarkPrimary = Color(0xFFA8C7FF)
internal val DarkOnPrimary = Color(0xFF003064)
internal val DarkPrimaryContainer = Color(0xFF004689)
internal val DarkOnPrimaryContainer = Color(0xFFD6E3FF)
internal val DarkSecondary = Color(0xFF75D5CF)
internal val DarkOnSecondary = Color(0xFF003735)
internal val DarkSecondaryContainer = Color(0xFF00504D)
internal val DarkOnSecondaryContainer = Color(0xFFB2F2ED)
internal val DarkTertiary = Color(0xFFCFBFFF)
internal val DarkOnTertiary = Color(0xFF3600A1)
internal val DarkTertiaryContainer = Color(0xFF5200D9)
internal val DarkOnTertiaryContainer = Color(0xFFE8DFFF)
internal val DarkError = Color(0xFFFFB4AB)
internal val DarkOnError = Color(0xFF690005)
internal val DarkErrorContainer = Color(0xFF93000A)
internal val DarkOnErrorContainer = Color(0xFFFFDAD6)
internal val DarkBackground = Color(0xFF0F141D)
internal val DarkOnBackground = Color(0xFFE0E3E9)
internal val DarkSurface = Color(0xFF171C26)
internal val DarkOnSurface = Color(0xFFE0E3E9)
internal val DarkSurfaceVariant = Color(0xFF434D5C)
internal val DarkOnSurfaceVariant = Color(0xFFC3CBD9)
internal val DarkOutline = Color(0xFF8D95A3)
internal val DarkOutlineVariant = Color(0xFF434D5C)
internal val DarkScrim = Color(0xFF000000)

val BrandGradientStart: Color = Primary
val BrandGradientEnd: Color = Secondary
